[package]
name = "rusty-color-shredder"
version = "0.2.0"
authors = ["gyatso"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
image = "*"
queues = "*"
rayon = "*"
palette = "*"
strict-yaml-rust = "*"