config:
  canvas:
    size:
      x: 512
      y: 128
    starting_locations:
      - x: 0
        y: 0
      - x: 512
        y: 512
        
  colors:
    # list of reference colors given in RGB
    reference_colors:
      - r: 0
        g: 159
        b: 219
      - r: 0
        g: 87
        b: 184
    # rgb or hsl
    use_hsv: true
    # color to hold constant
    color_channel_options:
      channel_1:
        lock: "false"
        clamp:
          min: "0.0"
          max: "1.0"
      channel_2:
        lock: "false"
        clamp:
          min: "0.0"
          max: "1.0"
      channel_3:
        lock: "false"
        clamp:
          min: "0.0"
          max: "1.0"
